//
//  AdviverseSKAdNetwork.swift
//  AdviverseSDK
//
//  SKAdNetwork (StoreKit ad-attribution) plumbing. The base SDK only MODELS the
//  `skadn` block (see `AdviverseSKAdNetwork` in Adviverse.swift); this file adds
//  the actual StoreKit registration: when the engine returns a SIGNED `skadn`
//  block for an iOS app-install campaign, the SDK registers the view-through
//  impression with StoreKit using the values the SERVER provided.
//
//  IMPORTANT CAVEAT (read before shipping):
//  ----------------------------------------
//  The cryptographic `signature` MUST be generated by the ad network's server
//  using its SKAdNetwork private key, per Apple's signing spec. The SDK does NOT
//  and CANNOT compute it — it takes the server-provided fields and hands them to
//  StoreKit verbatim. We therefore only register when `skadn.isSigned` is true
//  (i.e. NOT a placeholder signature); a malformed/placeholder/expired payload
//  is silently dropped by StoreKit anyway. This targets the SKAdImpression API
//  (SKAdNetwork 2.2+, iOS 14.5+) and must be validated on a real device against
//  a live, correctly-signed payload.
//

import Foundation

public extension Adviverse {

    /// Register the SKAdNetwork view-through impression for `ad`, if the engine
    /// supplied a SIGNED `skadn` block. Safe to call unconditionally — it no-ops
    /// when there is no payload, the signature is a placeholder, the OS is too
    /// old, or required fields are missing/malformed.
    ///
    /// Call this around the time the ad is presented (the full-screen presenters
    /// call it automatically alongside the impression beacon).
    static func registerSKAdNetworkImpression(for ad: AdviverseAd) {
        guard let s = ad.skAdNetwork, s.isSigned else { return }
        #if canImport(StoreKit) && os(iOS)
        if #available(iOS 14.5, *) {
            startSKAdImpression(s)
        }
        // iOS < 14.5: the SKAdImpression API is unavailable. The engine should
        // sign for SKAdNetwork 2.2+; we intentionally do not call the legacy
        // (pre-2.2) view-through API. No-op on older OSes.
        #endif
    }
}

#if canImport(StoreKit) && os(iOS)
import StoreKit

@available(iOS 14.5, *)
private extension Adviverse {

    /// Build an `SKAdImpression` from the server payload and register it as a
    /// view-through impression. The signature is taken as-is from the engine.
    static func startSKAdImpression(_ s: AdviverseSKAdNetwork) {
        // All of these are required by StoreKit; bail if the engine omitted any.
        guard
            !s.network.isEmpty,
            let campaign = decimalNumber(s.campaign),
            let itunesItem = decimalNumber(s.itunesItem),
            let nonceUUID = UUID(uuidString: s.nonce),
            !s.signature.isEmpty
        else { return }

        let imp = SKAdImpression()
        imp.adNetworkIdentifier = s.network                 // e.g. "example123.skadnetwork"
        imp.advertisedAppStoreItemIdentifier = itunesItem   // target app's App Store id
        imp.adImpressionIdentifier = nonceUUID.uuidString   // nonce (UUID string)
        imp.adCampaignIdentifier = campaign                 // SKAN campaign id (1...100 for <4.0)
        imp.timestamp = NSNumber(value: s.timestamp)
        imp.signature = s.signature                         // SERVER-SIGNED, never local
        imp.version = s.version                             // SKAdNetwork version string
        // Publisher app's App Store id — optional in the payload + the API.
        if let sourceApp = s.sourceApp, let sourceItem = decimalNumber(sourceApp) {
            imp.sourceAppStoreItemIdentifier = sourceItem
        }

        // View-through ("background") impression: start on render. If the user
        // converts (taps -> StoreKit overlay / store), the host can call
        // `SKAdNetwork.endImpression(_:)` to convert it to a click-through. We
        // start it here; ending is left to the click path since the
        // store-presentation API is host-specific.
        SKAdNetwork.startImpression(imp) { error in
            if let error = error {
                NSLog("AdviverseSDK SKAdNetwork.startImpression failed: \(error.localizedDescription)")
            }
        }
    }

    /// Parse a numeric field that may arrive as a JSON string or numeric.
    static func decimalNumber(_ s: String) -> NSNumber? {
        guard !s.isEmpty else { return nil }
        if let i = Int(s) { return NSNumber(value: i) }
        if let d = Double(s) { return NSNumber(value: d) }
        return nil
    }
}
#endif
